[build]
  command = "mkdir -p dist/static && cp -r frontend/static/* dist/static/ && cp frontend/static/index.html dist/index.html && cp -r frontend/locales dist/locales"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

